services:
  sionna:
    build:
      context: .
      dockerfile: Dockerfile.sionna
    volumes:
      - ./src/sionna/scenarios/SionnaExampleScenario:/sionna/scenarios/SionnaExampleScenario
    network_mode: host
    container_name: sionna-container
    healthcheck:
      test: ["CMD", "python3", "-c", "import http.client; conn = http.client.HTTPConnection('127.0.0.1', 8103); conn.request('GET', '/health'); res = conn.getresponse(); exit(0) if res.status == 200 else exit(1)"]
      interval: 10s
      timeout: 100s
      retries: 10
      start_period: 10s

  ns3:
    build:
      context: .
      dockerfile: Dockerfile.ns3
    depends_on:
      sionna:
        condition: service_healthy
    environment:
      - NS3_EXAMPLE="simple-sionna-example"
    network_mode: host
    container_name: ns3-container